[package]
name = "alu"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_runtime = "0.5.1"
log = "0.4.16"
serde = { version = "1.0.136", features = ["derive"] }
tokio = { version = "1.17.0", features = ["full"] }
